#!/usr/bin/env node

const config = require('./libs/config.js')();
const log = require('./libs/log.js')(config);
const sender = require('./libs/sender.js')(config, log);
const db = require('./libs/db.js')(config, log);

db.connect().then(() => {
	sender.listen((cc) => {
		db.addCaption(cc);
	});
});

