#!/usr/bin/env node

const config = require('./libs/config.js')();
const log = require('./libs/log.js')(config);
const connection = require('./libs/connection.js')(config, log);
const db = require('./libs/db.js')(config, log);

db.connect().then(() => {
	connection.connect((cc) => {
		db.addCaption(cc);
	});
});

